//ACCINES PARA CONTADOR
export const INCREMENT = 'INCREMENTO'
export const DECREMENT = 'DISMINUIR'
export const INCREMENT_5 = 'INCREMENTO_5'
export const DECREMENT_5 = 'DISMINUIR_5'
export const RESET = 'RESETEO'
export const INCRECLASS = 'INCREMENTARCLASES'
export const DECRECLASS = 'DECREMENTARCLASES'

//SHOPPING CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

//CRUD

export const CREATE_DATA = 'CREAR_DATOS'
export const READ_ALL_DATA = 'LEER_TODO_LOS_DATOS'
export const UPDATE_DATA = 'ACTUALIZAR_DATOS'
export const DELETE_DATA = 'ELIMINAR_DATOS'
export const NO_DATA = 'NO_HAY_DATOS'
